### ISSUE TITLE
Research and correct problems with invalid open and close dates

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#392]
Some open and close dates are invalid. Please determine the extent of these problematic dates and correct or remove them as needed.
![Screen Shot 2019-03-10 at 1.56.03 PM.png](https://images.zenhubusercontent.com/56e745406caf56c9d38dbb89/5d5abb08-0aa1-4ea7-a8ba-c137b2f8ba6e)

**Comment by tsyaeger** [comment]
@jjfreund When creating a Resource all data is created minus schedule days/times. Researched code base and found that invalid date comes from schedule_days created with nil opens_at and closes_at fields. I tried to create a resource on local machine with scheduled days and times, but found that the request is not passing schedule data to the server, resulting in nil vals. However, editing schedule_days works correctly for schedule fields.

Is there any other place/process in the app where resources are created (e.g. admin or task) with nil schedule opens_at/closes_at values? Since we already have nil values for those fields in the database, that means they were created somehow that I am probably not yet aware.

Also, I looked at the ScheduleDay model and found no validation in there. I think in order to prevent such nil values in the database, we should add a presence validation for the opens_at and closes_at fields. That will prevent these kinds of bad record creation in our database and possible resolve the invalid date issue moving forward.

**Comment by tsyaeger** [comment]
@jjfreund When creating a Resource all data is created minus schedule days/times. Researched code base and found that invalid date comes from schedule_days created with nil opens_at and closes_at fields. I tried to create a resource on local machine with scheduled days and times, but found that the request is not passing schedule data to the server, resulting in nil vals. However, editing schedule_days works correctly for schedule fields.

Is there any other place/process in the app where resources are created (e.g. admin or task) with nil schedule opens_at/closes_at values? Since we already have nil values for those fields in the database, that means they were created somehow that I am probably not yet aware.

Also, I looked at the ScheduleDay model and found no validation in there. I think in order to prevent such nil values in the database, we should add a presence validation for the opens_at and closes_at fields. That will prevent these kinds of bad record creation in our database and possible resolve the invalid date issue moving forward.

**Comment by tsyaeger** [comment]
Given the new day/time columns, I'll correct this issue by adapting the previous modifications to the change_request controller -- allowing deletion of a ScheduleDay.

https://github.com/ShelterTechSF/askdarcel-api/commit/47717a3ee76a7c98a979e6f9898de367a5b52e6b

**Comment by Maxastuart** [comment]
Mostly done - Reminder to create the ticket to change the check/test for verifying all times input are valid when we switch to "time" types instead of integers.
