### ISSUE TITLE
Populate factory girl mock categories with image icons

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-api#74]

**Comment by jfhamlin** [comment]
Instead of storing the icon filenames in the database, can the clients map category names to icon names by convention? It looks like `'ic-' + category.name.toLower().replace(' ', '-') + '@3x.png'` would work. And if it doesn't we can rename them so it does or use some other mapping. The files are in the web app anyway, so I don't think we gain much by returning icon names from the API.
